/* nome delle pizze in cui almeno un ingrediente ha quanitaMagazzino = 0*/
SELECT 
	P.NOME,
	P.CODPIZZA,
	I.NOME AS "INGREDIENTE DA COMPRARE"
FROM 
	PIZZE P
	JOIN RICETTE R USING (CODPIZZA)
	JOIN INGREDIENTI I USING (CODINGREDIENTE)
WHERE 
	I.QUANTITAMAGAZZINO = 0
